### ISSUE TITLE
关于文档公布的请求

### ISSUE THREAD

**Issue by RainyHallways** [bouldev/neo-omega-kernel#1]
neomega下属的文档能否在此仓库中公布？
感谢！

**Comment by CMA2401PT** [comment]
计划中，我们希望把lua代码和文档同时转移到一个开源仓库中，但是因为 lua 文件和 go 代码存在耦合，故目前还在计划中
但是我们可以先把文档单独打包发出来
[docs.zip](https://github.com/bouldev/neo-omega-kernel/files/14566438/docs.zip)

**Comment by RainyHallways** [comment]
感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月12日 10:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [bouldev/neo-omega-kernel] 关于文档公布的请求 (Issue #1) |

计划中，我们希望把lua代码和文档同时转移到一个开源仓库中，但是因为 lua 文件和 go 代码存在耦合，故目前还在计划中
但是我们可以先把文档单独打包发出来
docs.zip

**Comment by CMA2401PT** [comment]
尽管我们没能成功把所有我们觉得可以公布的文档全部从代码中集中到一处，我们还是决定先把比较容易的部分单独移动到一个开源仓库中。注意，此仓库还包含许多弃用且未公布的文档，出于兼容性考虑，请不要将弃用文档编入正式的公开位置中。
https://github.com/CMA2401PT/neomega-doc
未来我们将继续将文档集中到此公开仓库中
