### ISSUE TITLE
关于send_ws_cmd接口的问题

### ISSUE THREAD

**Issue by maoqijie** [bouldev/neo-omega-kernel#2]
在使用该接口获取返回值的时候，如果使用的指令中存在违禁词，将会导致这个进程完全卡住，希望可以解决这个问题
![Screenshot_20240223_210545](https://github.com/bouldev/neo-omega-kernel/assets/109787609/3ee24344-7cd2-437f-8e1e-9c98ddfb4945)
![Screenshot_20240223_210551](https://github.com/bouldev/neo-omega-kernel/assets/109787609/964978e7-d6a5-4fea-982a-c0fa5e9c5aec)

**Comment by CMA2401PT** [comment]
已经解决，见文档，最后一个参数可以填超时（秒）
