### ISSUE TITLE
关于send_ws_cmd接口的其他问题

### ISSUE THREAD

**Issue by maoqijie** [bouldev/neo-omega-kernel#3]
在使用send_ws_cmd接口获取计分板分数时，如果直接使用"scoreboard players 对象 add 计分板名字 0"，可以正常获取到计分板分数，但是如果套了一层exe，比如"execute @p ~ ~ ~ scoreboard players 对象 add 计分板名字 0"则无法正常获取计分板分数
希望大佬可以解决一下
![Screenshot_20240302_004245_com mmbox xbrowser](https://github.com/bouldev/neo-omega-kernel/assets/109787609/3f68228a-56ea-45bc-90aa-70658963e2f2)

**Comment by Happy2018new** [comment]
这看起来并不是一个 `BUG` ，因为你在游戏里面这么干也依然看不到加和的结果？

**Comment by CMA2401PT** [comment]
正如 Happy 所说，指令的执行结果受 mc 服务器控制
