### ISSUE TITLE
Failed to build `Access Point`

### ISSUE THREAD

**Issue by Happy2018new** [bouldev/neo-omega-kernel#4]
### Use
```sh
cd neomega_kernel/neomega/entries/access_point_entry/cli
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/neomega_linux_access_point_amd64
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o build/neomega_windows_access_point_amd64.exe
CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o build/neomega_linux_access_point_arm64
CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o build/neomega_windows_access_point_arm64.exe
CGO_CFLAGS= CGO_ENABLED=1 GOOS=android GOARCH=arm64 CC=${HOME}/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang CXX=${HOME}/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang++ go build -trimpath -ldflags="-s -w" -o build/neomega_android_access_point_arm64
```

### Output
```
# neo-omega-kernel/neomega/entries/minimal_end_point_entry
Error: ../../minimal_end_point_entry/entry.go:31:32: not enough arguments in call to node.ListenMessage
	have (string, func(msg nodes.Values))
	want (string, nodes.MsgListener, bool)
Error: Process completed with exit code 1.
```

### Helpful Links
See [ActionRuns](https://github.com/ToolDelta/ToolDelta-depends/actions/runs/8232501467/job/22510073470) for more details.

**Comment by CMA2401PT** [comment]
consider follow up-stream change, or provide your version info. currently we cannot reproduce this issue

**Comment by CMA2401PT** [comment]
can you reproduce this error in local machine?

**Comment by Happy2018new** [comment]
该问题仍然可以在最新的提交复现，以下是 `Termux` 中的复现结果。
***
![Screenshot_20240314_004224](https://github.com/bouldev/neo-omega-kernel/assets/109064184/850d5814-4cc8-4508-9093-c2e7eddaaf89)

**Comment by Happy2018new** [comment]
[ToolDelta-depends](https://github.com/ToolDelta/ToolDelta-depends) 中的 `Action` 会在每日执行两次，每次执行时会检测本存储库(neo-omega-kernel)是否创建了新的提交。如果创建了新的提交，则将会从该存储库拉取最新的提交，并编译对应的依赖，这其中包括 `Access Point` 。

现在每天都会连续两次收到编译失败的报告，您可以前往 [All-ActionRuns](https://github.com/ToolDelta/ToolDelta-depends/actions) 查看具体的信息。

**Comment by CMA2401PT** [comment]
出于一些原因（因为我没有切换到正确的repo）导致相关修改没有被提交，现在应该已经修复了，非常抱歉。

**Comment by CMA2401PT** [comment]
70aa85f3a80537bb5b34f49a0c95dfb4d1ac3502
