### ISSUE TITLE
关于在解释"无法连接租赁服原因"时出现的错字

### ISSUE THREAD

**Issue by xingchentye** [bouldev/neo-omega-kernel#5]
![image](https://github.com/bouldev/neo-omega-kernel/assets/123609288/95a6bfc6-7529-4f25-8e52-e50f1580bd9b)
我认为这个地方的内容应该是"重进"，如果这个词语是正常的，那请您关闭这个ISSUE！

**Comment by Liliya233** [comment]
Fixed 92a1c4c35ce28e2b0e1a246f9539653c4c476261
