### ISSUE TITLE
Server password is not expected to be shown when NeOmega launches

### ISSUE THREAD

**Issue by wangzm5573** [bouldev/neo-omega-kernel#6]
**Current situation:**
![image](https://github.com/bouldev/neo-omega-kernel/assets/121756620/e2bf0db1-9165-4293-84f9-e60f527e9daa)

**Expected situation:**
![image](https://github.com/bouldev/neo-omega-kernel/assets/121756620/ae8679a1-a254-49f9-8cf4-677ace99a9cd)

**Comment by Liliya233** [comment]
Fixed 12b77f787377c5f27550f2b9e6bb44dc74b6f4db
