### ISSUE TITLE
编译c_api时出现问题

### ISSUE THREAD

**Issue by xingchentye** [bouldev/neo-omega-kernel#9]
系统: Linux Debian 12
Golang Version: go1.22.4 linux/amd64
在使用go build -tags fbconn -o libfbconn.so -buildmode=c-shared main.go命令编译c_api的过程中出现
../../minecraft/protocol/packet/compression.go:10:2: no required module provides package github.com/golang/snappy; to add it:
        go get github.com/golang/snappy
(看了一眼go.mod中没有这个)
和另一个
../../../../.golang/pkg/mod/github.com/pterm/pterm@v0.12.29/terminal.go:6:2: missing go.sum entry for module providing package golang.org/x/term (imported by neo-omega-kernel/neomega/rental_server_impact/info_collect_utils); to add:
        go get neo-omega-kernel/neomega/rental_server_impact/info_collect_utils
(不太能理解，但是使用go get neo-omega-kernel/neomega/rental_server_impact/info_collect_utils成功的修复了)

**Comment by xingchentye** [comment]
如果是我的判断问题，在此致歉并请您关闭这个ISSUE!

**Comment by CMA2401PT** [comment]
good issue, solved 3c350ca4520420640a9538f7d93c280bfc2403f8
